//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4332
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityModel
    {
        public int Id { get; set; }
        public string Code_zakaza { get; set; }
        public string Date_create { get; set; }
        public string Code_client { get; set; }
        public string Uslugi { get; set; }
    }
}
