//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4332
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityModel2
    {
        public int Id { get; set; }
        public string CodeZakaza { get; set; }
        public string DateCreate { get; set; }
        public string TimeCreate { get; set; }
        public string CodeClient { get; set; }
        public string Uslugi { get; set; }
        public string State { get; set; }
        public string DateClosed { get; set; }
        public string Time_Prokat { get; set; }
    }
}
