//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template_4332
{
    using System;
    using System.Collections.Generic;
    
    public partial class workers
    {
        public int id { get; set; }
        public string job_title { get; set; }
        public string fio { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string last_entrance { get; set; }
        public string type_entrance { get; set; }

        public workers() { }

        public workers(int id, string job_title, string fio, string login, string password, string last_entrance, string type_entrance)
        {
            this.id = id;
            this.job_title = job_title;
            this.fio = fio;
            this.login = login;
            this.password = password;
            this.last_entrance = last_entrance;
            this.type_entrance = type_entrance;
        }
    }
}
